"""Add is_seller to customers

Revision ID: 13d7bff2ecde
Revises: fdcfbde7b7b9
Create Date: 2025-02-19 16:23:36.910457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d7bff2ecde'
down_revision = 'fdcfbde7b7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('is_seller')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seller', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_seller')

    # ### end Alembic commands ###
