"""Fix is_seller field

Revision ID: 805e4f3cad75
Revises: 5e96d69c400e
Create Date: 2025-02-18 20:01:28.853189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805e4f3cad75'
down_revision = '5e96d69c400e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('is_seller')

    # ### end Alembic commands ###
