"""Added username and password fields to Customer model

Revision ID: 861607cf522e
Revises: a09ad61a0b86
Create Date: 2025-02-12 16:14:58.757967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861607cf522e'
down_revision = 'a09ad61a0b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('_hash_password', sa.String(length=128), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('_hash_password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
